### ISSUE TITLE
Can not find hdf5 file

### ISSUE THREAD

**Issue by shane5713** [vdvchen/SGMNet#12]
When I run 
python dump.py --config_path configs/gl3d.yaml

I encounter the following issue, seems like it can not find hdf5 file
how to solve it?

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker    result = (True, func(*args, **kwds))  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/sshuang/SGMNet/datadump/dumper/gl3d_train.py", line 192, in format_seq
    with h5py.File(os.path.join(self.config['feature_dump_dir'],fea_path1),'r') as fea1, \
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/sshuang/SGMNet/datadump/dump_desc/000000000000000000000009/00000007.jpg_sp_500.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dump.py", line 27, in <module>
    dataset.format_dump_data()
  File "/home/sshuang/SGMNet/datadump/dumper/gl3d_train.py", line 244, in format_dump_data
    pool.map(self.format_seq,indices)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
OSError: Unable to open file (unable to open file: name = '/home/sshuang/SGMNet/datadump/dump_desc/000000000000000000000009/00000007.jpg_sp_500.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by shane5713** [comment]
I found that this error comes from wrong dataset.
I should download "gl3d_imgs", not "gl3d_raw_imgs".
